# Generated by Django 4.1.2 on 2022-10-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('dorm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dorm_address', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=30, unique=True)),
                ('food_price', models.FloatField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('is_in_stock', models.BooleanField(blank=True, default=True, null=True)),
                ('image', models.CharField(blank=True, max_length=30, null=True)),
                ('id_food_type', models.ForeignKey(db_column='id_food_type', on_delete=django.db.models.deletion.DO_NOTHING, to='stolovka.foodtype')),
            ],
        ),
    ]
